name: Deploy Streamlit Application to AWS EC2

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 Host to Known Hosts
      run: |
        ssh-keyscan -H ${{ vars.EC2_PUBLIC_DNS }} >> $HOME/.ssh/known_hosts

    - name: Check SSH Connection
      run: |
        ssh -vvv -o StrictHostKeyChecking=no ec2-user@ec2-18-212-203-146.compute-1.amazonaws.com "echo 'SSH Connection Successful'"

    - name: Ensure Deploy Directory Exists
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.EC2_USER }}@${{ vars.EC2_PUBLIC_DNS }} "mkdir -p ${{ vars.EC2_DEPLOY_PATH }}"

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' --delete ./ ${{ vars.EC2_USER }}@${{ vars.EC2_PUBLIC_DNS }}:${{ vars.EC2_DEPLOY_PATH }}
    
    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.EC2_USER }}@${{ vars.EC2_PUBLIC_DNS }} << 'EOF'
        # Check for Python and install if not exists
        if ! command -v python3 &> /dev/null
        then
            echo "Python3 is not installed. Installing Python3..."
            sudo apt-get update
            sudo apt-get install -y python3
        fi
    
        # Check for pip and install if not exists
        if ! command -v pip3 &> /dev/null
        then
            echo "pip3 is not installed. Installing pip3..."
            sudo apt-get install -y python3-pip
        fi
    
        # Ensure the virtual environment is set up
        if [ ! -d "${{ vars.EC2_DEPLOY_PATH }}/chatbot_env" ]
        then
            echo "Setting up virtual environment..."
            python3 -m venv ${{ vars.EC2_DEPLOY_PATH }}/chatbot_env
        fi
    
        # Activate virtual environment
        source ${{ vars.EC2_DEPLOY_PATH }}/chatbot_env/bin/activate

        # Upgrade pip
        python3 -m pip install --upgrade pip
    
        # Install dependencies
        pip install -r requirements.txt
    
        # Kill the currently running Streamlit app if any
        pkill -f streamlit || true  # Ignore errors if no process is found
    
        # Start Streamlit app
        nohup streamlit run app.py &
    
        EOF

        