name: Deploy Streamlit Application to AWS EC2

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}
      EC2_DEPLOY_PATH: ${{ secrets.EC2_DEPLOY_PATH }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz --exclude '.git*' --delete ./ ${{ vars.EC2_USER }}@${{ vars.EC2_PUBLIC_DNS }}:${{ vars.EC2_DEPLOY_PATH }}

    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.EC2_USER }}@${{ vars.EC2_PUBLIC_DNS }} << EOF
          cd ${{ vars.EC2_DEPLOY_PATH }}
          source myenv/bin/activate  # Activate virtual environment if needed
          pip install -r requirements.txt  # Install dependencies
          pkill -f streamlit  # Kill the currently running Streamlit app
          nohup streamlit run app.py --server.port 80 &  # Run Streamlit app in the background on port 80
        EOF